#!/usr/bin/env python
#coding:utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import urllib
import requests 
import urllib2
import sys
import bz2
from os.path import join
HOST = '180.153.136.14:8888'
HOST_HTTP = 'http://%s'%HOST
#API_URL = '%s/:api/txt/'%HOST_HTTP
API_URL = '%s/txt/'%HOST_HTTP

def help():
    print """
1.Paste file to cp2cc
  hi@Mars ~$ cp2cc < foo.txt  
  http://42qu.cc/txt/xa47qt471
2.Custom url 
  hi@Mars ~$ cp2cc hi < foo.txt
  http://42qu.cc/hi
3.Save web page to local file
  hi@Mars ~$ cp2cc  http://42qu.cc/txt/xa47qt471  >  foo.txt
    """

def post(url=''):
    data = ''.join(sys.stdin.readlines())
    files = {'file': ('txt', bz2.compress(data) )}
    try:
        r = requests.post(API_URL+url, files=files, timeout=300)
    except Exception,e:
        print 'can not connect server'
    else:
        print HOST_HTTP+"/"+r.text

def main():
    argv = sys.argv
    url = ''
    if len(argv) > 1:
        if len(argv) > 2:
            help()
            return
        url = argv[1]
        if url.startswith(HOST_HTTP):
            url = url[len(HOST_HTTP)+1:] 
            try:
                r = requests.get(API_URL+url, timeout=300) 
            except Exception,e:
                print 'can not connect server'
            else:
                print r.text
            return
        else:
            url = argv[1].lstrip("/")

    post(url)

if __name__ == '__main__':
    main()
