{u'defines': [{u'define': [{u'name': u'VERSION_MAJOR', u'value': u'0'},
                           {u'name': u'VERSION_MINOR', u'value': u'8'},
                           {u'name': u'VERSION_REVISION', u'value': u'0'},
                           {u'name': u'SESSION_KEY_LEN', u'value': u'33'},
                           {u'name': u'NAME_LEN', u'value': u'64'},
                           {u'name': u'EQUIPMENT_ID_LEN', u'value': u'33'},
                           {u'name': u'EQUIPMENT_ICON_LEN',
                            u'value': u'33'},
                           {u'name': u'EQUIPMENT_RES_LEN', u'value': u'33'},
                           {u'name': u'EQUIPMENT_GRADE_LEN',
                            u'value': u'20'},
                           {u'name': u'EQUIPMENT_TYPE_LEN',
                            u'value': u'50'},
                           {u'name': u'EQUIPMENT_PRICETYPE_LEN',
                            u'value': u'20'},
                           {u'name': u'MAX_COMMAND_LEN', u'value': u'512'},
                           {u'name': u'MAX_TEXT_LEN', u'value': u'512'}]}],
 u'messages': [{u'message': [{u'dir': u'cs',
                              u'id': u'2000',
                              u'name': u'MSG_LOGIN_REQ',
                              u'type': u'CLI_GS_LOGIN_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2001',
                              u'name': u'MSG_LOGIN_ACK',
                              u'type': u'GS_CLI_LOGIN_ACK'},
                             {u'dir': u'cs',
                              u'id': u'2003',
                              u'name': u'MSG_PING_REQ',
                              u'type': u'CLI_GS_PING_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2004',
                              u'name': u'MSG_PING_ACK',
                              u'type': u'GS_CLI_PING_ACK'},
                             {u'dir': u'cs',
                              u'id': u'2010',
                              u'name': u'MSG_MOVE_REQ',
                              u'type': u'CLI_GS_MOVE_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2011',
                              u'name': u'MSG_MOVE_NTF',
                              u'type': u'GS_CLI_MOVE_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2012',
                              u'name': u'MSG_MOVE_ACK',
                              u'type': u'GS_CLI_MOVE_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2013',
                              u'name': u'MSG_PROPERTYCHANGED_INT_NTF',
                              u'type': u'GS_CLI_PROPERTYCHANGED_INT_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2014',
                              u'name': u'MSG_PROPERTYCHANGED_UINT_NTF',
                              u'type': u'GS_CLI_PROPERTYCHANGED_UINT_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2015',
                              u'name': u'MSG_PROPERTYCHANGED_FLOAT_NTF',
                              u'type': u'GS_CLI_PROPERTYCHANGED_FLOAT_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2016',
                              u'name': u'MSG_FORCE_REPOSITIONED_NTF',
                              u'type': u'GS_CLI_FORCE_REPOSITIONED_NTF'},
                             {u'dir': u'cs',
                              u'id': u'2017',
                              u'name': u'MSG_CREATURE_PROPERTIES_REQ',
                              u'type': u'CLI_GS_CREATURE_PROPERTIES_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2018',
                              u'name': u'MSG_CREATURE_PROPERTIES_ACK',
                              u'type': u'GS_CLI_CREATURE_PROPERTIES_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2019',
                              u'name': u'MSG_JUMP_NTF',
                              u'type': u'GS_CLI_JUMP_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2020',
                              u'name': u'MSG_SKILL_PROPERTIES_NTF',
                              u'type': u'GS_CLI_SKILL_PROPERTIES_NTF'},
                             {u'dir': u'cs',
                              u'id': u'2022',
                              u'name': u'MSG_CASTING_REQ',
                              u'type': u'CLI_GS_CASTING_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2023',
                              u'name': u'MSG_CASTING_NTF',
                              u'type': u'GS_CLI_CASTING_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2024',
                              u'name': u'MSG_CASTED_NTF',
                              u'type': u'GS_CLI_CASTED_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2025',
                              u'name': u'MSG_CASTING_ACK',
                              u'type': u'GS_CLI_CASTING_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2026',
                              u'name': u'MSG_SKILL_COOLDOWN_NTF',
                              u'type': u'GS_CLI_SKILL_COOLDOWN_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2030',
                              u'name': u'MSG_CREATURE_APPEAR_NTF',
                              u'type': u'GS_CLI_CREATURE_APPEAR_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2031',
                              u'name': u'MSG_CREATURE_DISAPPEAR_NTF',
                              u'type': u'GS_CLI_CREATURE_DISAPPEAR_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2032',
                              u'name': u'MSG_CREATURE_ON_NTF',
                              u'type': u'GS_CLI_CREATURE_ON_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2033',
                              u'name': u'MSG_CREATURE_OFF_NTF',
                              u'type': u'GS_CLI_CREATURE_OFF_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2034',
                              u'name': u'MSG_OPERATOR_APPEAR_NTF',
                              u'type': u'GS_CLI_OPERATOR_APPEAR_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2035',
                              u'name': u'MSG_OPERATOR_DISAPPEAR_NTF',
                              u'type': u'GS_CLI_OPERATOR_DISAPPEAR_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2040',
                              u'name': u'MSG_ADD_BUFF_NTF',
                              u'type': u'GS_CLI_ADD_BUFF_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2041',
                              u'name': u'MSG_UPDATE_BUFF_NTF',
                              u'type': u'GS_CLI_UPDATE_BUFF_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2042',
                              u'name': u'MSG_DEL_BUFF_NTF',
                              u'type': u'GS_CLI_DEL_BUFF_NTF'},
                             {u'dir': u'cs',
                              u'id': u'2050',
                              u'name': u'MSG_MOVE_EQUIPMENT_REQ',
                              u'type': u'CLI_GS_MOVE_EQUIPMENT_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2060',
                              u'name': u'MSG_MOVE_EQUIPMENT_ACK',
                              u'type': u'GS_CLI_MOVE_EQUIPMENT_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2070',
                              u'name': u'MSG_MOVE_EQUIPMENT_NTF',
                              u'type': u'GS_CLI_MOVE_EQUIPMENT_NTF'},
                             {u'dir': u'cs',
                              u'id': u'2080',
                              u'name': u'MSG_DROP_EQUIPMENT_REQ',
                              u'type': u'CLI_GS_DROP_EQUIPMENT_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2081',
                              u'name': u'MSG_DROP_EQUIPMENT_ACK',
                              u'type': u'GS_CLI_DROP_EQUIPMENT_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2110',
                              u'name': u'MSG_UPDATED_EQUIPMENT_NTF',
                              u'type': u'GS_CLI_UPDATED_EQUIPMENT_NTF'},
                             {u'dir': u'cs',
                              u'id': u'2120',
                              u'name': u'MSG_LIST_EQUIPMENT_REQ',
                              u'type': u'CLI_GS_LIST_EQUIPMENT_REQ'},
                             {u'dir': u'sc',
                              u'id': u'2130',
                              u'name': u'MSG_LIST_EQUIPMENT_ACK',
                              u'type': u'GS_CLI_LIST_EQUIPMENT_ACK'},
                             {u'dir': u'sc',
                              u'id': u'2140',
                              u'name': u'MSG_LIST_EQUIPMENT_NTF',
                              u'type': u'GS_CLI_LIST_EQUIPMENT_NTF'},
                             {u'dir': u'sc',
                              u'id': u'2150',
                              u'name': u'MSG_SIMPLE_MESSAGE_NTF',
                              u'type': u'GS_CLI_SIMPLE_MESSAGE_NTF'},
                             {u'dir': u'cs',
                              u'id': u'3101',
                              u'name': u'MSG_COMMAND_REQ',
                              u'type': u'CLI_GS_COMMAND_REQ'},
                             {u'dir': u'sc',
                              u'id': u'3102',
                              u'name': u'MSG_COMMAND_ACK',
                              u'type': u'GS_CLI_COMMAND_ACK'},
                             {u'dir': u'cs',
                              u'id': u'4120',
                              u'name': u'MSG_TASK_REQ',
                              u'type': u'CLI_GS_TASK_REQ'},
                             {u'dir': u'cs',
                              u'id': u'4130',
                              u'name': u'MSG_CHANGE_TABLE_REQ',
                              u'type': u'CLI_GS_CHANGE_TABLE_REQ'},
                             {u'dir': u'sc',
                              u'id': u'4131',
                              u'name': u'MSG_CHANGE_TABLE_ACK',
                              u'type': u'GS_CLI_CHANGE_TABLE_ACK'},
                             {u'dir': u'cs',
                              u'id': u'4132',
                              u'name': u'MSG_ASSIGN_LEADER_REQ',
                              u'type': u'CLI_GS_ASSIGN_LEADER_REQ'},
                             {u'dir': u'sc',
                              u'id': u'4133',
                              u'name': u'MSG_ASSIGN_LEADER_ACK',
                              u'type': u'GS_CLI_ASSIGN_LEADER_ACK'},
                             {u'dir': u'cs',
                              u'id': u'4200',
                              u'name': u'MSG_LOCK_PLAYER_REQ',
                              u'type': u'CLI_GS_LOCK_PLAYER_REQ'},
                             {u'dir': u'sc',
                              u'id': u'4300',
                              u'name': u'MSG_WINNER_NTF',
                              u'type': u'GS_CLI_WINNER_NTF'},
                             {u'dir': u'sc',
                              u'id': u'4401',
                              u'name': u'MSG_SPEAK_NTF',
                              u'type': u'GS_CLI_SPEAK_NTF'},
                             {u'dir': u'cs',
                              u'id': u'4402',
                              u'name': u'MSG_TALK_REQ',
                              u'type': u'CLI_GS_TALK_REQ'},
                             {u'dir': u'sc',
                              u'id': u'4403',
                              u'name': u'MSG_TALK_ACK',
                              u'type': u'GS_CLI_TALK_ACK'}]}],
 u'name': u'BnFGameProto',
 u'types': [{u'type': [{u'item': [{u'count': u'SESSION_KEY_LEN',
                                   u'name': u'SessionKey',
                                   u'type': u'string'},
                                  {u'name': u'UserId', u'type': u'dword'},
                                  {u'name': u'TableId', u'type': u'int'},
                                  {u'name': u'major', u'type': u'int'},
                                  {u'name': u'minor', u'type': u'int'},
                                  {u'name': u'revision', u'type': u'int'}],
                        u'name': u'CLI_GS_LOGIN_REQ'},
                       {u'item': [{u'name': u'ErrCode', u'type': u'int'},
                                  {u'name': u'Id', u'type': u'int'}],
                        u'name': u'GS_CLI_LOGIN_ACK'},
                       {u'item': [{u'name': u'Data', u'type': u'dword'}],
                        u'name': u'CLI_GS_PING_REQ'},
                       {u'item': [{u'name': u'Data', u'type': u'dword'}],
                        u'name': u'GS_CLI_PING_ACK'},
                       {u'item': [{u'name': u'Type', u'type': u'dword'},
                                  {u'name': u'Career', u'type': u'dword'},
                                  {u'name': u'Gender', u'type': u'byte'},
                                  {u'count': u'NAME_LEN',
                                   u'name': u'Name',
                                   u'type': u'string'},
                                  {u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'UserId', u'type': u'dword'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'},
                                  {u'name': u'Radius', u'type': u'float'},
                                  {u'name': u'MovementSpeed',
                                   u'type': u'float'},
                                  {u'name': u'Health', u'type': u'float'},
                                  {u'name': u'Hp', u'type': u'float'},
                                  {u'name': u'Mana', u'type': u'float'},
                                  {u'name': u'Mp', u'type': u'float'},
                                  {u'name': u'CampId', u'type': u'byte'},
                                  {u'name': u'ForceId', u'type': u'byte'},
                                  {u'name': u'Attackable',
                                   u'type': u'byte'},
                                  {u'name': u'Talkable',
                                   u'type': u'byte'},
                                  {u'name': u'MonsterClass',
                                   u'type': u'int'},
                                  {u'name': u'TableId', u'type': u'int'},
                                  {u'name': u'State', u'type': u'int'},
                                  {u'name': u'Level', u'type': u'dword'},
                                  {u'name': u'isBuilding',
                                   u'type': u'byte'}],
                        u'name': u'GS_CLI_CREATURE_APPEAR_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'}],
                        u'name': u'GS_CLI_CREATURE_DISAPPEAR_NTF'},
                       {u'item': [{u'count': u'NAME_LEN',
                                   u'name': u'Name',
                                   u'type': u'string'},
                                  {u'name': u'Id', u'type': u'dword'}],
                        u'name': u'GS_CLI_CREATURE_ON_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'}],
                        u'name': u'GS_CLI_CREATURE_OFF_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'}],
                        u'name': u'CLI_GS_CREATURE_PROPERTIES_REQ'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'count': u'NAME_LEN',
                                   u'name': u'Name',
                                   u'type': u'string'},
                                  {u'name': u'Exp', u'type': u'int'},
                                  {u'name': u'PreExp', u'type': u'int'},
                                  {u'name': u'NextExp', u'type': u'int'},
                                  {u'name': u'Level', u'type': u'int'},
                                  {u'name': u'Hp', u'type': u'float'},
                                  {u'name': u'Mp', u'type': u'float'},
                                  {u'name': u'Health', u'type': u'float'},
                                  {u'name': u'HealthRegeneration',
                                   u'type': u'float'},
                                  {u'name': u'Mana', u'type': u'float'},
                                  {u'name': u'ManaRegeneration',
                                   u'type': u'float'},
                                  {u'name': u'AttackDamage',
                                   u'type': u'float'},
                                  {u'name': u'AbilityPower',
                                   u'type': u'float'},
                                  {u'name': u'Armor', u'type': u'float'},
                                  {u'name': u'ArmorPenetration',
                                   u'type': u'float'},
                                  {u'name': u'MagicResistance',
                                   u'type': u'float'},
                                  {u'name': u'MagicPenetration',
                                   u'type': u'float'},
                                  {u'name': u'CriticalStrikeChance',
                                   u'type': u'float'},
                                  {u'name': u'CriticalStrikeDamage',
                                   u'type': u'float'},
                                  {u'name': u'LifeSteal',
                                   u'type': u'float'},
                                  {u'name': u'SpellVamp',
                                   u'type': u'float'},
                                  {u'name': u'Tenacity',
                                   u'type': u'float'},
                                  {u'name': u'Range', u'type': u'float'},
                                  {u'name': u'MovementSpeed',
                                   u'type': u'float'},
                                  {u'name': u'AttackSpeed',
                                   u'type': u'float'},
                                  {u'name': u'CooldownReduction',
                                   u'type': u'float'},
                                  {u'name': u'Gold', u'type': u'dword'},
                                  {u'name': u'RMB', u'type': u'dword'},
                                  {u'name': u'GM', u'type': u'dword'}],
                        u'name': u'GS_CLI_CREATURE_PROPERTIES_ACK'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'Type', u'type': u'int'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'},
                                  {u'name': u'SubType', u'type': u'int'},
                                  {u'name': u'Arg1', u'type': u'dword'},
                                  {u'name': u'Arg2', u'type': u'dword'}],
                        u'name': u'GS_CLI_OPERATOR_APPEAR_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'}],
                        u'name': u'GS_CLI_OPERATOR_DISAPPEAR_NTF'},
                       {u'item': [{u'name': u'n', u'type': u'dword'}],
                        u'name': u'GS_CLI_SIMPLE_MESSAGE_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'Class', u'type': u'dword'},
                                  {u'name': u'Level', u'type': u'dword'},
                                  {u'name': u'PreCastTime',
                                   u'type': u'float'},
                                  {u'name': u'CastTime',
                                   u'type': u'float'},
                                  {u'name': u'CastingTime',
                                   u'type': u'float'},
                                  {u'name': u'Cooldown',
                                   u'type': u'float'},
                                  {u'name': u'Range', u'type': u'float'},
                                  {u'name': u'SmallCD',
                                   u'type': u'float'},
                                  {u'name': u'MiddleCD',
                                   u'type': u'float'},
                                  {u'name': u'BigCD', u'type': u'float'},
                                  {u'name': u'MP', u'type': u'int'},
                                  {u'name': u'AttackMin',
                                   u'type': u'int'},
                                  {u'name': u'AttackMax',
                                   u'type': u'int'},
                                  {u'name': u'MagicAttackMin',
                                   u'type': u'int'},
                                  {u'name': u'MagicAttackMax',
                                   u'type': u'int'},
                                  {u'name': u'Damage', u'type': u'int'},
                                  {u'name': u'Arg1', u'type': u'float'},
                                  {u'name': u'Arg2', u'type': u'float'},
                                  {u'name': u'Arg3', u'type': u'float'},
                                  {u'name': u'Arg4', u'type': u'float'}],
                        u'name': u'GS_CLI_SKILL_PROPERTIES_NTF'},
                       {u'item': [{u'name': u'ClientSideId',
                                   u'type': u'dword'},
                                  {u'count': u'MAX_COMMAND_LEN',
                                   u'name': u'Command',
                                   u'type': u'string'}],
                        u'name': u'CLI_GS_COMMAND_REQ'},
                       {u'item': [{u'name': u'ClientSideId',
                                   u'type': u'dword'},
                                  {u'count': u'MAX_COMMAND_LEN',
                                   u'name': u'Result',
                                   u'type': u'string'}],
                        u'name': u'GS_CLI_COMMAND_ACK'},
                       {u'item': [{u'name': u'State', u'type': u'int'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'}],
                        u'name': u'CLI_GS_MOVE_REQ'},
                       {u'item': [{u'name': u'Id', u'type': u'int'},
                                  {u'name': u'State', u'type': u'int'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'}],
                        u'name': u'GS_CLI_MOVE_NTF'},
                       {u'item': [{u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'}],
                        u'name': u'GS_CLI_MOVE_ACK'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'},
                                  {u'name': u'Speed', u'type': u'float'},
                                  {u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'ModifierId',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_FORCE_REPOSITIONED_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Angle', u'type': u'float'}],
                        u'name': u'GS_CLI_JUMP_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'PropertyId',
                                   u'type': u'int'},
                                  {u'name': u'Value', u'type': u'int'},
                                  {u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'ModifierId',
                                   u'type': u'dword'},
                                  {u'name': u'Arg1', u'type': u'dword'}],
                        u'name': u'GS_CLI_PROPERTYCHANGED_INT_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'PropertyId',
                                   u'type': u'int'},
                                  {u'name': u'Value', u'type': u'dword'},
                                  {u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'ModifierId',
                                   u'type': u'dword'},
                                  {u'name': u'Arg1', u'type': u'dword'}],
                        u'name': u'GS_CLI_PROPERTYCHANGED_UINT_NTF'},
                       {u'item': [{u'name': u'Id', u'type': u'dword'},
                                  {u'name': u'PropertyId',
                                   u'type': u'int'},
                                  {u'name': u'Value', u'type': u'float'},
                                  {u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'ModifierId',
                                   u'type': u'dword'},
                                  {u'name': u'Arg1', u'type': u'dword'}],
                        u'name': u'GS_CLI_PROPERTYCHANGED_FLOAT_NTF'},
                       {u'item': [{u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'SkillSeq',
                                   u'type': u'dword'},
                                  {u'name': u'TargetId',
                                   u'type': u'dword'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'}],
                        u'name': u'CLI_GS_CASTING_REQ'},
                       {u'item': [{u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'SkillSeq',
                                   u'type': u'dword'},
                                  {u'name': u'ErrorId',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_CASTING_ACK'},
                       {u'item': [{u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'SkillSeq',
                                   u'type': u'dword'},
                                  {u'name': u'PlayerId',
                                   u'type': u'dword'},
                                  {u'name': u'TargetId',
                                   u'type': u'dword'},
                                  {u'name': u'X', u'type': u'float'},
                                  {u'name': u'Y', u'type': u'float'},
                                  {u'name': u'Lame', u'type': u'dword'}],
                        u'name': u'GS_CLI_CASTING_NTF'},
                       {u'item': [{u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'SkillSeq',
                                   u'type': u'dword'},
                                  {u'name': u'PlayerId',
                                   u'type': u'dword'},
                                  {u'name': u'TargetId',
                                   u'type': u'dword'},
                                  {u'name': u'ResultId',
                                   u'type': u'byte'}],
                        u'name': u'GS_CLI_CASTED_NTF'},
                       {u'item': [{u'name': u'SkillId',
                                   u'type': u'dword'},
                                  {u'name': u'Cooldown',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_SKILL_COOLDOWN_NTF'},
                       {u'item': [{u'name': u'PlayerId',
                                   u'type': u'dword'},
                                  {u'name': u'BuffId', u'type': u'dword'},
                                  {u'name': u'BuffLevel',
                                   u'type': u'int'},
                                  {u'name': u'BuffTime',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_ADD_BUFF_NTF'},
                       {u'item': [{u'name': u'PlayerId',
                                   u'type': u'dword'},
                                  {u'name': u'BuffId', u'type': u'dword'},
                                  {u'name': u'BuffLevel',
                                   u'type': u'int'},
                                  {u'name': u'BuffTime',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_UPDATE_BUFF_NTF'},
                       {u'item': [{u'name': u'PlayerId',
                                   u'type': u'dword'},
                                  {u'name': u'BuffId', u'type': u'dword'}],
                        u'name': u'GS_CLI_DEL_BUFF_NTF'},
                       {u'item': [{u'name': u'OwnerId',
                                   u'type': u'dword'},
                                  {u'count': u'EQUIPMENT_ID_LEN',
                                   u'name': u'EquipmentId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_ICON_LEN',
                                   u'name': u'IconId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_RES_LEN',
                                   u'name': u'EquipmentRes',
                                   u'type': u'string'},
                                  {u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ItemType',
                                   u'type': u'byte'},
                                  {u'name': u'Count', u'type': u'int'},
                                  {u'count': u'EQUIPMENT_TYPE_LEN',
                                   u'name': u'EquipmentType',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_GRADE_LEN',
                                   u'name': u'Grade',
                                   u'type': u'string'},
                                  {u'name': u'TemplateId',
                                   u'type': u'dword'},
                                  {u'name': u'Special', u'type': u'int'}],
                        u'name': u'GS_CLI_UPDATED_EQUIPMENT_NTF'},
                       {u'item': [{u'name': u'OwnerId',
                                   u'type': u'dword'},
                                  {u'name': u'Bag', u'type': u'byte'},
                                  {u'name': u'Equipment',
                                   u'type': u'byte'}],
                        u'name': u'CLI_GS_LIST_EQUIPMENT_REQ'},
                       {u'item': [{u'name': u'OwnerId',
                                   u'type': u'dword'},
                                  {u'count': u'EQUIPMENT_ID_LEN',
                                   u'name': u'EquipmentId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_ICON_LEN',
                                   u'name': u'IconId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_RES_LEN',
                                   u'name': u'EquipmentRes',
                                   u'type': u'string'},
                                  {u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ItemType',
                                   u'type': u'byte'},
                                  {u'name': u'Count', u'type': u'int'},
                                  {u'count': u'EQUIPMENT_TYPE_LEN',
                                   u'name': u'EquipmentType',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_GRADE_LEN',
                                   u'name': u'Grade',
                                   u'type': u'string'},
                                  {u'name': u'TemplateId',
                                   u'type': u'dword'},
                                  {u'name': u'Special', u'type': u'int'}],
                        u'name': u'GS_CLI_LIST_EQUIPMENT_ACK'},
                       {u'item': [{u'name': u'OwnerId',
                                   u'type': u'dword'},
                                  {u'count': u'EQUIPMENT_ID_LEN',
                                   u'name': u'EquipmentId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_ICON_LEN',
                                   u'name': u'IconId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_RES_LEN',
                                   u'name': u'EquipmentRes',
                                   u'type': u'string'},
                                  {u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ItemType',
                                   u'type': u'byte'},
                                  {u'name': u'Count', u'type': u'int'},
                                  {u'count': u'EQUIPMENT_TYPE_LEN',
                                   u'name': u'EquipmentType',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_GRADE_LEN',
                                   u'name': u'Grade',
                                   u'type': u'string'},
                                  {u'name': u'TemplateId',
                                   u'type': u'dword'},
                                  {u'name': u'Special', u'type': u'int'}],
                        u'name': u'GS_CLI_LIST_EQUIPMENT_NTF'},
                       {u'item': [{u'name': u'Position',
                                   u'type': u'byte'}],
                        u'name': u'CLI_GS_DROP_EQUIPMENT_REQ'},
                       {u'item': [{u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ErrorId',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_DROP_EQUIPMENT_ACK'},
                       {u'item': [{u'name': u'SourceOwnerId',
                                   u'type': u'dword'},
                                  {u'name': u'PositionFrom',
                                   u'type': u'byte'},
                                  {u'name': u'PositionTo',
                                   u'type': u'byte'}],
                        u'name': u'CLI_GS_MOVE_EQUIPMENT_REQ'},
                       {u'item': [{u'name': u'ErrorId',
                                   u'type': u'dword'},
                                  {u'count': u'EQUIPMENT_ID_LEN',
                                   u'name': u'EquipmentId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_ICON_LEN',
                                   u'name': u'IconId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_RES_LEN',
                                   u'name': u'EquipmentRes',
                                   u'type': u'string'},
                                  {u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ItemType',
                                   u'type': u'byte'},
                                  {u'name': u'Count', u'type': u'int'},
                                  {u'count': u'EQUIPMENT_TYPE_LEN',
                                   u'name': u'EquipmentType',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_GRADE_LEN',
                                   u'name': u'Grade',
                                   u'type': u'string'},
                                  {u'name': u'TemplateId',
                                   u'type': u'dword'},
                                  {u'name': u'Special', u'type': u'int'}],
                        u'name': u'GS_CLI_MOVE_EQUIPMENT_ACK'},
                       {u'item': [{u'name': u'OwnerId',
                                   u'type': u'dword'},
                                  {u'count': u'EQUIPMENT_ID_LEN',
                                   u'name': u'EquipmentId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_ICON_LEN',
                                   u'name': u'IconId',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_RES_LEN',
                                   u'name': u'EquipmentRes',
                                   u'type': u'string'},
                                  {u'name': u'Position',
                                   u'type': u'byte'},
                                  {u'name': u'ItemType',
                                   u'type': u'byte'},
                                  {u'name': u'Count', u'type': u'int'},
                                  {u'count': u'EQUIPMENT_TYPE_LEN',
                                   u'name': u'EquipmentType',
                                   u'type': u'string'},
                                  {u'count': u'EQUIPMENT_GRADE_LEN',
                                   u'name': u'Grade',
                                   u'type': u'string'},
                                  {u'name': u'TemplateId',
                                   u'type': u'dword'},
                                  {u'name': u'Special', u'type': u'int'}],
                        u'name': u'GS_CLI_MOVE_EQUIPMENT_NTF'},
                       {u'item': [{u'name': u'TaskId', u'type': u'dword'},
                                  {u'name': u'TaskState',
                                   u'type': u'dword'}],
                        u'name': u'CLI_GS_TASK_REQ'},
                       {u'item': [{u'name': u'TableId', u'type': u'int'}],
                        u'name': u'CLI_GS_CHANGE_TABLE_REQ'},
                       {u'item': [{u'name': u'TableId', u'type': u'int'}],
                        u'name': u'GS_CLI_CHANGE_TABLE_ACK'},
                       {u'item': [{u'name': u'NewLeaderId',
                                   u'type': u'dword'}],
                        u'name': u'CLI_GS_ASSIGN_LEADER_REQ'},
                       {u'item': [{u'name': u'ResultId', u'type': u'int'}],
                        u'name': u'GS_CLI_ASSIGN_LEADER_ACK'},
                       {u'item': [{u'name': u'Lock', u'type': u'byte'}],
                        u'name': u'CLI_GS_LOCK_PLAYER_REQ'},
                       {u'item': [{u'name': u'ForceId',
                                   u'type': u'dword'}],
                        u'name': u'GS_CLI_WINNER_NTF'},
                       {u'item': [{u'name': u'SpeakerId',
                                   u'type': u'dword'},
                                  {u'count': u'MAX_TEXT_LEN',
                                   u'name': u'Content',
                                   u'type': u'string'}],
                        u'name': u'GS_CLI_SPEAK_NTF'},
                       {u'item': [{u'name': u'TargetId',
                                   u'type': u'dword'}],
                        u'name': u'CLI_GS_TALK_REQ'},
                       {u'item': [{u'name': u'ResultId', u'type': u'int'}],
                        u'name': u'GS_CLI_TALK_ACK'}]}],
 u'version': u'1'}
